### PR TITLE
allow regex for --exclude

### PR DESCRIPTION
**Pull request by markus-wa**

### CODE REVIEW

**Comment by peioe** [comment]
Does this work from the config file ? I tried with this line:
exclude = ['.+\.png', '.+\.ogg', '.+\.pdf', '.+\.cue', '.+\.log']

But it still copied everything.

**Comment by markus-wa** [comment]
woops, the config file example was wrong.

the wrapping single quotes `'` should only be used for `opusenc_args` with leading `--`. try

    exclude = [.+.png, .+.ogg, .+.pdf, .+.cue', .+.log]

**Comment by peioe** [comment]
Thanks !

**Comment by peioe** [comment]
It's copying all the .png files still. Any idea what it could be ?

**Comment by markus-wa** [comment]
Can you make sure you've got the latest version?

```
$ python3 to_opus.py -c cfg -s tests/source -t out   
...

$ cat cfg
exclude = [.+\.txt]                                                                                                                                                                       

$ la tests/source/nested/text.txt
-rwxrwxrwx 1 root root 0 Mar 29 19:44 tests/source/nested/text.txt

$ la out/nested/text.txt
ls: cannot access 'out/nested/text.txt': No such file or directory
```

PS: the `\` before `.` shouldn't be required. it's just to make sure the `.` is interpreted literally instead of as a wildcard

**Comment by markus-wa** [comment]
> It's copying all the .png files still. Any idea what it could be ?

just png or also all the other types you're trying to exclude?

**Comment by peioe** [comment]
My bad, I must have messed something up. I started fresh with a clean repo and config and it's all good now :) Thanks !

**Pull request merged**
